variables:
   VERSION: 1.0.${CI_PIPELINE_ID}

stages:
   - deploy

deploy-k8s:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - export KUBECONFIG=$KUBECONFIG_FILE
    - helm
