variables:
   VERSION: 1.0.${CI_PIPELINE_ID}

stages:
   - deploy

deploy-k8s:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - export KUBECONFIG=$KUBECONFIG_FILE
    - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get-helm-3 > get_helm.sh
    - chmod 700 get_helm.sh
    - ./get_helm.sh
    - helm
