variables:
   VERSION: 1.0.${CI_PIPELINE_ID}

stages:
   - deploy

deploy-k8s:
  stage: deploy
  image:
    name: dtzar/helm-kubectl:latest
    entrypoint: ['']
  script:
    - export KUBECONFIG=$KUBECONFIG_FILE
    - helm repo add --username $NEXUS_USER --password $NEXUS_PASS nexus https://nexus.praktikum-services.tech/repository/sausage-store-helm-gleb-fedotov-24
    - helm repo update 
    - helm upgrade --install sausage-store --set ingress.host="fedotov-gleb-24.k8s.praktikum-services.tech" --atomic --timeout 15m nexus/sausage-store
