- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 16.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_16.x bionic main
    update_cache: yes
    
- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present
    
- name: "Install http-server"
  npm:
    global: yes
    name: http-server   
    
- name: Set cap_net_bind_service+eip on /usr/bin/node
  community.general.capabilities:
    path: /usr/bin/node
    capability: cap_net_bind_service+eip
    state: present
    
