frontend:
  image: gitlab.praktikum-services.ru:5050/std-024-07/sausage-store/sausage-frontend
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80

imagePullSecrets: 
  name: docker-config-secret
