{{- if .Values.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "backend-report.fullname" . }}
  labels:
    {{- include "backend-report.labels" . | nindent 4 }}
spec:
  minReplicas: {{ .Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "backend-report.fullname" . }}
  metrics:
  {{- if .Values.autoscaling.hpa.averageUtilization }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.hpa.averageUtilization }}
  {{- end }}
{{- end }}  
