---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }} 
  labels:
    {{- include "backend.labels" . | nindent 4 }} 
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
