- name: Create bsckend system service from template
  template:
    src: sausage-store-backend.j2
    dest: /etc/systemd/system/sausage-store-backend.service
    owner: "{{ backend_user }}"
    group: "{{ backend_group }}" 

- name: Reload systemd configuration
  systemd:
    daemon_reload: yes

- name: Run backend system service!
  service:
    name: sausage-store-backend
    enabled: true
    state: started
